// Food Nutrition Database — extracted from Sheet 19 "日常食物营养率"
// Each entry: { zh, en, rate, gi, note_zh, note_en }
// rate = carb rate or protein rate depending on category

const FOOD_CATEGORIES = [
  { id: 'rice',    zh: '米类主食',     en: 'Rice Staples' },
  { id: 'wheat',   zh: '麦类主食',     en: 'Wheat Staples' },
  { id: 'other',   zh: '其他主食',     en: 'Other Staples' },
  { id: 'instant', zh: '方便食品',     en: 'Instant Foods' },
  { id: 'portable',zh: '便携碳水',     en: 'Portable Carbs' },
  { id: 'fruit',   zh: '水果',         en: 'Fruits' },
  { id: 'protein', zh: '蛋白质来源',   en: 'Protein Sources' },
  { id: 'fat',     zh: '脂肪说明',     en: 'Fat Guide' },
];

const FOODS = {
  rice: [
    {zh:'生米',       en:'Raw rice',           rate:0.75, gi:'high', noteZh:'大米/糙米/糯米/小米/紫米/黑米碳水率近似', noteEn:'All rice varieties have similar carb rates'},
    {zh:'米饭（很软）', en:'Rice (very soft)',   rate:0.25, gi:'high', noteZh:'仅自己做饭才可能这么软', noteEn:'Only possible when cooking at home'},
    {zh:'米饭（一般）', en:'Rice (regular)',     rate:0.30, gi:'high', noteZh:'外卖标准米饭，长方形盒约100-120g碳水', noteEn:'Standard takeout rice, ~100-120g carbs per rectangular box'},
    {zh:'米饭（偏硬）', en:'Rice (firm)',        rate:0.35, gi:'high', noteZh:'外卖偏硬米饭', noteEn:'Firmer takeout rice'},
    {zh:'米粥（稀）',  en:'Rice porridge (thin)',rate:0.10, gi:'high', noteZh:'粘稠度类似小米粥', noteEn:'Consistency like millet porridge'},
    {zh:'米粥（一般）', en:'Rice porridge (regular)',rate:0.13,gi:'high', noteZh:'比小米粥更稠', noteEn:'Thicker than millet porridge'},
    {zh:'米线（熟）',  en:'Rice noodles (cooked)',rate:0.33,gi:'high', noteZh:'饱腹感很低，外食一般≥100g碳水/份', noteEn:'Very low satiety, typically ≥100g carbs per serving'},
    {zh:'肠粉（熟）',  en:'Rice noodle rolls',  rate:0.20, gi:'high', noteZh:'广东主食，一般50-70g碳水/份', noteEn:'Cantonese staple, ~50-70g carbs per serving'},
    {zh:'粽子',       en:'Zongzi (sticky rice)',rate:0.50, gi:'high', noteZh:'白粽/豆沙粽可吃，不吃肉粽；40-60g碳水/个', noteEn:'Plain or red bean only, skip meat ones; 40-60g carbs each'},
  ],
  wheat: [
    {zh:'切片面包',    en:'Sliced bread',       rate:0.50, gi:'high', noteZh:'普通切片脂肪率<8%是碳水；花式面包脂肪率>15%是糖油混合物', noteEn:'Plain <8% fat = carb food; fancy >15% fat = junk'},
    {zh:'馒头/花卷/馍/馕',en:'Steamed bun/Flatbread',rate:0.50,gi:'high', noteZh:'', noteEn:''},
    {zh:'挂面（生）',  en:'Dried noodles (raw)', rate:0.75, gi:'mid',  noteZh:'中GI，不建议用于练后餐', noteEn:'Medium GI, not ideal for post-workout'},
    {zh:'意面（生）',  en:'Pasta (raw)',         rate:0.75, gi:'low',  noteZh:'低GI，不能用于练后餐', noteEn:'Low GI, cannot use for post-workout'},
    {zh:'鲜面（生）',  en:'Fresh noodles (raw)', rate:0.60, gi:'high', noteZh:'现和现拉面条，外食一般≥100g碳水/份', noteEn:'Fresh pulled noodles, ≥100g carbs per serving eating out'},
    {zh:'凉面（熟）',  en:'Cold noodles (cooked)',rate:0.30,gi:'high', noteZh:'', noteEn:''},
    {zh:'粗面（熟）',  en:'Thick noodles (cooked)',rate:0.30,gi:'high', noteZh:'吸水率比细面低，碳水率稍高；外食≥100g碳水/份', noteEn:'Less water absorption than thin noodles'},
    {zh:'意面（熟）',  en:'Pasta (cooked)',      rate:0.30, gi:'low',  noteZh:'低GI，不能用于练后餐', noteEn:'Low GI, not for post-workout'},
    {zh:'细面（熟）',  en:'Thin noodles (cooked)',rate:0.23,gi:'high', noteZh:'吸水率高碳水率稍低；外食≥100g碳水/份', noteEn:'High water absorption, eating out ≥100g carbs/serving'},
    {zh:'卷饼/烙饼/馕（熟）',en:'Wrap/Flatbread (cooked)',rate:0.50,gi:'high',noteZh:'饱腹感很低，外食一般≥100g碳水/份', noteEn:'Very low satiety, ≥100g carbs per serving'},
  ],
  other: [
    {zh:'红薯（生/蒸煮）',en:'Sweet potato (raw/steamed)',rate:0.18,gi:'high',noteZh:'',noteEn:''},
    {zh:'红薯（烤）',  en:'Sweet potato (baked)',rate:0.23, gi:'high', noteZh:'', noteEn:''},
    {zh:'土豆（生/蒸煮）',en:'Potato (raw/steamed)',rate:0.18,gi:'mid',noteZh:'',noteEn:''},
    {zh:'土豆（烤）',  en:'Potato (baked)',      rate:0.23, gi:'high', noteZh:'', noteEn:''},
    {zh:'红薯/土豆粉丝（生）',en:'Sweet potato/potato vermicelli (raw)',rate:0.84,gi:'low',noteZh:'低GI碳水(酸辣粉/红薯粉/土豆粉)，米粉米线不属此类',noteEn:'Low GI; includes sour-spicy noodles, not rice noodles'},
    {zh:'甜玉米（蒸煮）',en:'Sweet corn (steamed)',rate:0.20,gi:'mid',noteZh:'传统玉米，不建议用于练后餐',noteEn:'Traditional corn, not for post-workout'},
    {zh:'糯玉米（蒸煮）',en:'Waxy corn (steamed)',rate:0.35,gi:'high',noteZh:'口味软糯香味重，碳水率和GI比甜玉米高',noteEn:'Softer, more fragrant, higher carb/GI than sweet corn'},
    {zh:'贝贝南瓜',   en:'Baby pumpkin',         rate:0.21, gi:'mid',  noteZh:'注意贝贝南瓜和传统南瓜碳水率差别极大', noteEn:'Note huge carb difference vs regular pumpkin'},
    {zh:'传统南瓜',   en:'Regular pumpkin',      rate:0.05, gi:'mid',  noteZh:'碳水率远低于贝贝南瓜', noteEn:'Much lower carb than baby pumpkin'},
    {zh:'山药（蒸煮）',en:'Chinese yam (steamed)',rate:0.12, gi:'mid',  noteZh:'', noteEn:''},
    {zh:'藕粉（生）', en:'Lotus root starch (raw)',rate:0.90,gi:'low',  noteZh:'低GI碳水，不要用于练后餐；必须开水冲调', noteEn:'Low GI, not for post-workout; must use boiling water'},
    {zh:'燕麦麸皮（生）',en:'Oat bran (raw)',     rate:0.45, gi:'low',  noteZh:'低GI碳水；饱腹感极强；极高膳食纤维', noteEn:'Low GI; extremely filling; very high fiber'},
    {zh:'速食燕麦片（生）',en:'Instant oats (raw)',rate:0.60,gi:'high', noteZh:'饱腹感极强，一般不用于练后餐；极高膳食纤维', noteEn:'Very filling, generally not post-workout; very high fiber'},
    {zh:'速食黑麦片（生）',en:'Instant rye flakes (raw)',rate:0.60,gi:'high',noteZh:'饱腹感极强；脂肪率比燕麦片低；极高膳食纤维',noteEn:'Very filling; lower fat than oats; very high fiber'},
  ],
  instant: [
    {zh:'五谷道场方便面',en:'Wugu Daochang instant noodles',rate:0.65,gi:'mid',noteZh:'碳水约50g/袋；面饼非油炸；高钠建议粉包减半',noteEn:'~50g carbs/pack; non-fried; high sodium, use half seasoning'},
    {zh:'辛拉面（普通版）',en:'Shin Ramyun (regular)',rate:0.65,gi:'mid',noteZh:'碳水约50g；面饼油炸但调料包无油；高钠',noteEn:'~50g carbs; fried noodles but oil-free seasoning; high sodium'},
    {zh:'辛拉面（空空面版）',en:'Shin Ramyun (air-dried)',rate:0.65,gi:'mid',noteZh:'碳水约50g；面饼非油炸调料包无油；高钠',noteEn:'~50g carbs; non-fried, oil-free; high sodium'},
    {zh:'康力快熟意大利面',en:'Kangli quick-cook pasta',rate:0.32,gi:'low',noteZh:'碳水约60g/袋；低GI，不要用于练后餐',noteEn:'~60g carbs/pack; low GI, not for post-workout'},
    {zh:'白家陈记酸辣粉丝',en:'Baijia Chenji hot-sour vermicelli',rate:0.60,gi:'low',noteZh:'碳水40g/袋或60g/盒；低GI不用于练后餐；高钠',noteEn:'40-60g carbs; low GI not post-workout; high sodium'},
  ],
  portable: [
    {zh:'切片面包/碱水面包',en:'Sliced bread/Pretzel bread',rate:0.50,gi:'high',noteZh:'脂肪<8%是碳水食物；花式面包脂肪>15%是轻度糖油混合物',noteEn:'<8% fat = carb food; >15% fat = mild junk'},
    {zh:'旺仔小馒头（46g装）',en:'Wangzai mini buns (46g)',rate:0.88,gi:'high',noteZh:'碳水37g/袋；约1/4是蔗糖，不宜常作练后餐',noteEn:'37g carbs/pack; ~1/4 sucrose, limit post-workout use'},
    {zh:'旺仔QQ糖',   en:'Wangzai QQ gummies',  rate:0.72, gi:'high', noteZh:'小包20g装碳水15g；大包70g装碳水50g', noteEn:'Small 20g=15g carbs; Large 70g=50g carbs'},
    {zh:'南方黑芝麻糊（无蔗糖版）',en:'Nanfang black sesame paste (sugar-free)',rate:0.70,gi:'high',noteZh:'碳水35g/袋；脂肪很低是碳水食物；已熟化温水冲泡',noteEn:'35g carbs/pack; very low fat; pre-cooked, add warm water'},
    {zh:'南方高山玉米糊（无蔗糖版）',en:'Nanfang corn paste (sugar-free)',rate:0.70,gi:'high',noteZh:'碳水35g/袋；已熟化温水冲泡',noteEn:'35g carbs/pack; pre-cooked, add warm water'},
    {zh:'营养米粉',   en:'Nutritional rice cereal',rate:0.75,gi:'high', noteZh:'搜索"营养米粉/营养米糊"；已熟化温水冲泡',noteEn:'Search "nutritional rice cereal"; pre-cooked, add warm water'},
    {zh:'十月稻田饭团',en:'Shiyue rice ball',     rate:0.25, gi:'mid',  noteZh:'碳水25g/袋，开袋即食', noteEn:'25g carbs/pack, ready to eat'},
    {zh:'红螺牌驴打滚',en:'Hongluo ludagun (rice cake)',rate:0.86,gi:'high',noteZh:'碳水10g/小袋；麦芽糖而非蔗糖，无果糖超标问题',noteEn:'10g carbs/pack; uses maltose not sucrose, no fructose issue'},
    {zh:'山西烤馍',   en:'Shanxi baked bun',      rate:0.70, gi:'high', noteZh:'大袋装保质期长，口味类似葱香饼干', noteEn:'Large pack, long shelf life, tastes like onion crackers'},
    {zh:'非油炸干脆面',en:'Non-fried crunchy noodles',rate:0.75,gi:'mid',noteZh:'碳水27g/袋；口味类似小浣熊',noteEn:'27g carbs/pack; tastes like regular crunchy noodles'},
    {zh:'非油炸锅巴', en:'Non-fried rice crust',  rate:0.65, gi:'mid',  noteZh:'碳水65g/袋', noteEn:'65g carbs/pack'},
    {zh:'BHB熟板栗',  en:'BHB cooked chestnuts',  rate:0.35, gi:'mid',  noteZh:'碳水35g/袋', noteEn:'35g carbs/pack'},
    {zh:'沈大成豆沙青团',en:'Shendacheng red bean mochi',rate:0.65,gi:'high',noteZh:'碳水45g/个；只能是豆沙味，其他口味脂肪太高',noteEn:'45g carbs each; red bean only, other flavors too fatty'},
    {zh:'云片糕/桃片',en:'Rice flour cake slices',rate:0.80,gi:'high', noteZh:'小袋装，蔗糖率约10%', noteEn:'Small pack, ~10% sucrose'},
    {zh:'米花糖',     en:'Puffed rice candy',     rate:0.85, gi:'high', noteZh:'小袋装，蔗糖率约10%', noteEn:'Small pack, ~10% sucrose'},
    {zh:'娃哈哈八宝粥（木糖醇版）',en:'Wahaha congee (xylitol)',rate:0.13,gi:'high',noteZh:'碳水47g/罐；木糖醇版不产生果糖',noteEn:'47g carbs/can; xylitol version, no fructose'},
    {zh:'宝矿力运动饮料',en:'Pocari Sweat',       rate:0.06, gi:'mid',  noteZh:'30g蔗糖/瓶；不能作为练后全部碳水', noteEn:'30g sucrose/bottle; not enough for full post-workout carbs'},
    {zh:'脉动运动饮料',en:'Mizone sports drink',  rate:0.05, gi:'mid',  noteZh:'30g蔗糖/瓶；不能作为练后全部碳水', noteEn:'30g sucrose/bottle; not for full post-workout carbs'},
  ],
  fruit: [
    {zh:'干枣',       en:'Dried jujube',         rate:0.50, gi:'mid', noteZh:'', noteEn:''},
    {zh:'鲜枣',       en:'Fresh jujube',         rate:0.30, gi:'mid', noteZh:'', noteEn:''},
    {zh:'椰肉',       en:'Coconut meat',         rate:0.30, gi:'mid', noteZh:'', noteEn:''},
    {zh:'榴莲',       en:'Durian',               rate:0.28, gi:'mid', noteZh:'', noteEn:''},
    {zh:'菠萝蜜',     en:'Jackfruit',            rate:0.26, gi:'mid', noteZh:'', noteEn:''},
    {zh:'香蕉',       en:'Banana',               rate:0.22, gi:'mid', noteZh:'约20-30g碳水/根', noteEn:'~20-30g carbs each'},
    {zh:'提子',       en:'Table grapes',         rate:0.17, gi:'mid', noteZh:'', noteEn:''},
    {zh:'荔枝',       en:'Lychee',               rate:0.17, gi:'mid', noteZh:'', noteEn:''},
    {zh:'桂圆',       en:'Longan',               rate:0.17, gi:'mid', noteZh:'', noteEn:''},
    {zh:'猕猴桃',     en:'Kiwi',                 rate:0.15, gi:'mid', noteZh:'', noteEn:''},
    {zh:'苹果',       en:'Apple',                rate:0.13, gi:'low', noteZh:'约20-30g碳水/个', noteEn:'~20-30g carbs each'},
    {zh:'梨',         en:'Pear',                 rate:0.13, gi:'low', noteZh:'', noteEn:''},
    {zh:'车厘子',     en:'Cherry',               rate:0.13, gi:'low', noteZh:'', noteEn:''},
    {zh:'火龙果',     en:'Dragon fruit',         rate:0.13, gi:'mid', noteZh:'', noteEn:''},
    {zh:'芒果',       en:'Mango',                rate:0.13, gi:'mid', noteZh:'', noteEn:''},
    {zh:'桑葚',       en:'Mulberry',             rate:0.13, gi:'low', noteZh:'', noteEn:''},
    {zh:'葡萄',       en:'Grapes',               rate:0.12, gi:'low', noteZh:'', noteEn:''},
    {zh:'橘子',       en:'Tangerine',            rate:0.12, gi:'low', noteZh:'', noteEn:''},
    {zh:'橙子',       en:'Orange',               rate:0.11, gi:'low', noteZh:'约20-30g碳水/个', noteEn:'~20-30g carbs each'},
    {zh:'桃',         en:'Peach',                rate:0.10, gi:'low', noteZh:'', noteEn:''},
    {zh:'柚子',       en:'Pomelo',               rate:0.10, gi:'low', noteZh:'', noteEn:''},
    {zh:'樱桃',       en:'Sweet cherry',         rate:0.10, gi:'low', noteZh:'', noteEn:''},
    {zh:'西梅',       en:'Plum',                 rate:0.10, gi:'low', noteZh:'', noteEn:''},
    {zh:'枇杷',       en:'Loquat',               rate:0.09, gi:'low', noteZh:'', noteEn:''},
    {zh:'李子',       en:'Asian plum',           rate:0.09, gi:'low', noteZh:'', noteEn:''},
    {zh:'杏',         en:'Apricot',              rate:0.09, gi:'low', noteZh:'', noteEn:''},
    {zh:'哈密瓜',     en:'Hami melon',           rate:0.08, gi:'high',noteZh:'', noteEn:''},
    {zh:'西瓜',       en:'Watermelon',           rate:0.07, gi:'high',noteZh:'', noteEn:''},
    {zh:'木瓜',       en:'Papaya',               rate:0.07, gi:'mid', noteZh:'', noteEn:''},
    {zh:'圣女果（小番茄）',en:'Cherry tomato',   rate:0.06, gi:'low', noteZh:'', noteEn:''},
    {zh:'西红柿（大番茄）',en:'Tomato',          rate:0.03, gi:'low', noteZh:'', noteEn:''},
  ],
  protein: [
    {zh:'瘦肉（鱼虾生肉）',en:'Lean meat (raw fish/shrimp)',rate:0.15,gi:'',noteZh:'鱼虾含水率高于家禽家畜，蛋白质率稍低',noteEn:'Higher water content than poultry/livestock'},
    {zh:'瘦肉（三文鱼/金枪鱼）',en:'Lean meat (salmon/tuna)',rate:0.20,gi:'',noteZh:'中腧/赤身无油生食可视作瘦肉',noteEn:'Lean cuts eaten raw without oil can count as lean'},
    {zh:'瘦肉（家禽家畜生肉）',en:'Lean meat (raw poultry/livestock)',rate:0.20,gi:'',noteZh:'鸡鸭肉去皮，猪牛羊肉无白色脂肪层',noteEn:'Skinless poultry, no white fat layer on red meat'},
    {zh:'瘦肉（一般的熟肉）',en:'Lean meat (regular cooked)',rate:0.25,gi:'',noteZh:'鱼虾/家禽/家畜瘦肉均属之，不用区分品种',noteEn:'All lean cooked meat, no need to distinguish'},
    {zh:'瘦肉（柴感的熟肉）',en:'Lean meat (dry cooked)',rate:0.30,gi:'',noteZh:'酱牛肉、干柴卤肉，脱水率高蛋白质率更高',noteEn:'Beef jerky style, higher protein from dehydration'},
    {zh:'瘦肉干',     en:'Dried lean meat',      rate:0.40, gi:'',    noteZh:'牛肉干/鸡肉干，注意碳水率(糖率)最好<10%', noteEn:'Beef/chicken jerky, watch sugar content <10%'},
    {zh:'蛋白粉',     en:'Protein powder',       rate:0.75, gi:'',    noteZh:'乳清蛋白70-80%；分离乳清80-90%；大豆分离蛋白也可', noteEn:'Whey 70-80%; isolate 80-90%; soy isolate ok too'},
    {zh:'鸡蛋',       en:'Egg (whole)',          rate:6,    gi:'',    noteZh:'全蛋:蛋白质6g+脂肪5g；蛋清3g蛋白；蛋黄3g蛋白+5g脂肪', noteEn:'Whole: 6g protein + 5g fat; White: 3g protein; Yolk: 3g protein + 5g fat'},
    {zh:'牛奶',       en:'Milk (250ml)',         rate:10,   gi:'',    noteZh:'250ml盒装:碳水12g+蛋白质10g+脂肪9g，简记为碳蛋脂各10g', noteEn:'250ml: 12g carbs + 10g protein + 9g fat'},
    {zh:'酸奶',       en:'Yogurt (200ml)',       rate:10,   gi:'',    noteZh:'代糖酸奶≈纯牛奶；含糖酸奶多10g+糖；希腊酸奶近乎零脂', noteEn:'Artificially sweetened ≈ milk; sugared +10g sugar; Greek nearly fat-free'},
    {zh:'干黄豆',     en:'Dried soybeans',       rate:0.35, gi:'',    noteZh:'碳水34%+蛋白质35%+脂肪16%；不能替代瘦肉', noteEn:'34% carbs+35% protein+16% fat; cannot replace lean meat'},
    {zh:'鲜黄豆/毛豆/青豆',en:'Fresh soybeans/edamame',rate:0.13,gi:'',noteZh:'碳水11%+蛋白质13%+脂肪5%；不能替代瘦肉',noteEn:'11% carbs+13% protein+5% fat; cannot replace lean meat'},
    {zh:'豆皮/千张',  en:'Tofu skin',            rate:0.35, gi:'',    noteZh:'碳水20%+蛋白质35%+脂肪20%；不能替代瘦肉', noteEn:'20% carbs+35% protein+20% fat; cannot replace lean meat'},
    {zh:'豆腐',       en:'Tofu',                 rate:0.07, gi:'',    noteZh:'碳水3%+蛋白质7%+脂肪5%；不能替代瘦肉', noteEn:'3% carbs+7% protein+5% fat; cannot replace lean meat'},
    {zh:'豆浆',       en:'Soy milk',             rate:0.03, gi:'',    noteZh:'碳水1%+蛋白质3%+脂肪2%；热量很低可忽略；肯麦高甜豆浆≈糖水', noteEn:'Mostly water, negligible calories; fast-food soy milk ≈ sugar water'},
  ],
  fat: [
    {zh:'脂肪简化法', en:'Simplified Fat Method', rate:0, gi:'',
     noteZh:'鸡蛋牛奶+菜肴带油+排除高脂肉和糖油混合物=脂肪摄入合适，无需计算',
     noteEn:'Eggs/milk + cooking oil in dishes + avoid fatty meat & junk = adequate fat, no counting needed'},
    {zh:'菜肴带油说明',en:'Cooking Oil Guide', rate:0, gi:'',
     noteZh:'瘦肉菜前提下：a.排除煎炒鸡蛋 b.排除油烧茄子 c.减少干煸菜肴 d.重油菜可刮油或过水',
     noteEn:'With lean meat dishes: a. no fried eggs b. no oil-cooked eggplant c. limit dry-fried dishes d. scrape or rinse heavy-oil dishes'},
    {zh:'排除高脂肉', en:'Exclude High-Fat Meat', rate:0, gi:'',
     noteZh:'不是瘦肉：鸡鸭皮、大排、糖醋里脊、锅包肉、鸡翅、猪蹄、牛腩、牛排、排骨、烤肉、炸肉、午餐肉、肥牛、肥羊、肉肠、肉饼、肉馅、肉丸',
     noteEn:'NOT lean: skin, ribs, sweet-sour pork, battered meat, wings, trotters, brisket, steak, BBQ, fried meat, luncheon meat, fatty lamb/beef, sausage, patties, meatballs'},
    {zh:'排除糖油混合物',en:'Exclude Junk Food', rate:0, gi:'',
     noteZh:'饼干/蛋糕/点心/糕点/甜品/油条/煎饼/花式面包/膨化食品—碳水:脂肪<3:1即是糖油混合物，会让脂肪摄入超标',
     noteEn:'Cookies/cake/pastry/dessert/fried dough/ fancy bread/puffed snacks — carb:fat ratio <3:1 = junk, will exceed fat limit'},
  ]
};

// Helper: get food name in current language
function foodName(f) {
  const lang = document.documentElement.lang === 'en' ? 'en' : 'zh';
  return lang === 'en' ? f.en : f.zh;
}

function foodNote(f) {
  const lang = document.documentElement.lang === 'en' ? 'en' : 'zh';
  return lang === 'en' ? (f.noteEn || '') : (f.noteZh || '');
}
